unique_ids:
  assets:
    standard-page.html: IJDGXZ4CGQAA4VYWDOMGXPPOEJND6RMW
    theme.css: LPNQ7TTCFKK5V3QLBPUXANBDMMD5VQR5
  forms:
    Login: '1743004502427764075927997.3408'
    Simulator: I6CF4YGIKUGIREAN5S2W465XWJQRV52I
  modules: {}
  scripts: {}
  server_modules: {}
